name: Build
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  sonarcloud:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install SonarScanner
      uses: SonarSource/sonarqube-scan-action@v4

    - name: Run SonarCloud Scan
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        sonar-scanner.bat \
          -Dsonar.projectKey=johannsh_lab_rab \
          -Dsonar.organization=johannsh \
          -Dsonar.host.url="https://sonarcloud.io"

